"""Valid and invalid artifact corpora for validator tests."""

from __future__ import annotations


VALID_ARTIFACTS = [
    {
        "artifact_type": "pet",
        "tier": 1,
        "base_attack": 2,
        "base_health": 2,
        "trigger_type": "Faint",
        "target_type": "RandomFriend",
        "effect_type": "BuffFriend",
        "effect_value": 1,
        "cap_or_cooldown": 1,
        "cost": 3,
        "tags": ["early_game", "tempo"],
        "source": "valid_corpus",
    },
    {
        "artifact_type": "pet",
        "tier": 2,
        "base_attack": 3,
        "base_health": 3,
        "trigger_type": "Hurt",
        "target_type": "RandomEnemy",
        "effect_type": "DamageEnemy",
        "effect_value": 2,
        "cap_or_cooldown": 1,
        "cost": 3,
        "tags": ["tempo"],
        "source": "valid_corpus",
    },
    {
        "artifact_type": "pet",
        "tier": 3,
        "base_attack": 4,
        "base_health": 4,
        "trigger_type": "Faint",
        "target_type": "Self",
        "effect_type": "Summon",
        "effect_value": 2,
        "cap_or_cooldown": 1,
        "cost": 3,
        "tags": ["summon", "risk"],
        "source": "valid_corpus",
    },
    {
        "artifact_type": "pet",
        "tier": 4,
        "base_attack": 5,
        "base_health": 4,
        "trigger_type": "Sell",
        "target_type": "Self",
        "effect_type": "GoldGain",
        "effect_value": 2,
        "cap_or_cooldown": 1,
        "cost": 3,
        "tags": ["economy", "utility"],
        "source": "valid_corpus",
    },
]


INVALID_ARTIFACTS = [
    # Missing required key.
    {
        "artifact_type": "pet",
        "tier": 1,
        "base_attack": 2,
        "base_health": 2,
        "trigger_type": "Faint",
        "target_type": "RandomFriend",
        "effect_type": "BuffFriend",
        "effect_value": 1,
        "cap_or_cooldown": 1,
        "tags": ["tempo"],
    },
    # Invalid enum value.
    {
        "artifact_type": "pet",
        "tier": 1,
        "base_attack": 2,
        "base_health": 2,
        "trigger_type": "OnMoonrise",
        "target_type": "RandomFriend",
        "effect_type": "BuffFriend",
        "effect_value": 1,
        "cap_or_cooldown": 1,
        "cost": 3,
        "tags": ["tempo"],
    },
    # Hard constraint: buff cannot target enemy.
    {
        "artifact_type": "pet",
        "tier": 2,
        "base_attack": 3,
        "base_health": 3,
        "trigger_type": "Hurt",
        "target_type": "RandomEnemy",
        "effect_type": "BuffFriend",
        "effect_value": 1,
        "cap_or_cooldown": 1,
        "cost": 3,
        "tags": ["tempo"],
    },
    # Hard constraint: summon invalid trigger.
    {
        "artifact_type": "pet",
        "tier": 3,
        "base_attack": 4,
        "base_health": 4,
        "trigger_type": "Sell",
        "target_type": "Self",
        "effect_type": "Summon",
        "effect_value": 2,
        "cap_or_cooldown": 1,
        "cost": 3,
        "tags": ["summon"],
    },
    # Hard constraint: excessive power.
    {
        "artifact_type": "pet",
        "tier": 1,
        "base_attack": 10,
        "base_health": 10,
        "trigger_type": "Faint",
        "target_type": "RandomFriend",
        "effect_type": "BuffFriend",
        "effect_value": 4,
        "cap_or_cooldown": 1,
        "cost": 3,
        "tags": ["tempo"],
    },
    # Safety constraint: high effect without cooldown.
    {
        "artifact_type": "pet",
        "tier": 3,
        "base_attack": 2,
        "base_health": 2,
        "trigger_type": "Hurt",
        "target_type": "RandomEnemy",
        "effect_type": "DamageEnemy",
        "effect_value": 4,
        "cap_or_cooldown": 0,
        "cost": 3,
        "tags": ["debuff"],
    },
    # Strict pet-only check.
    {
        "artifact_type": "food",
        "tier": 2,
        "base_attack": 0,
        "base_health": 1,
        "trigger_type": "BuyFood",
        "target_type": "RandomFriend",
        "effect_type": "BuffFriend",
        "effect_value": 1,
        "cap_or_cooldown": 1,
        "cost": 3,
        "tags": ["utility"],
    },
]
